### PR TITLE
1 Setup Codebase

### PR DESCRIPTION
**Pull request by frinzekt**
## Change Summary
- dockerfile and compose
- frontend setup
- backend setup
- automated test CI scripts
- deployment for documentation
- documentation setup
- mailhog setup (system for mailing)
- linting frontend and backend

### Change Form
**Fill this up (NA if not available). If a certain criteria is not met, can you please give a reason.**

- [x] The pull request title has an issue number
- [x] The change works by "Smoke testing" or quick testing
- [x] The change has tests
- [ ] The change has documentation

## Other Information

### CODE REVIEW

**Review by MouseAndKeyboard — CHANGES_REQUESTED** [review]
Please describe codebase structure in documentation

**Comment by frinzekt** [comment]
hey @MouseAndKeyboard , I have added a basic documentation

**Comment by frinzekt** [comment]
@uwasystemhealth/redbacks  please watch the recording and MS teams for this changes and read this pull request. Ask questions if you don't understand a part of it

**Review by MouseAndKeyboard — APPROVED** [review]
looks epic

**Pull request merged**
